// test_emitter.cpp — Unit tests for LLVM IR emitter
#include <cassert>
#include <iostream>
#include <string>
#include "../include/flux/emitter.hpp"
#include "../include/flux/solver.hpp"

using namespace flux;

void test_emit_empty() {
    LLVMEmitter emitter;
    std::vector<Clause> clauses;
    std::string ir = emitter.emit_module(clauses);

    assert(!ir.empty());
    assert(ir.find("source_filename") != std::string::npos);
    assert(ir.find("target triple") != std::string::npos);
    assert(ir.find("Generated by flux::LLVMEmitter") != std::string::npos);

    std::cout << "  ✓ Emit empty module\n";
}

void test_emit_single_clause() {
    LLVMEmitter emitter;
    std::vector<Clause> clauses = {{1, -2, 3}};

    std::string ir = emitter.emit_module(clauses);
    assert(!ir.empty());
    assert(ir.find("constraint_0") != std::string::npos);
    assert(ir.find("check_all_clauses") != std::string::npos);
    assert(ir.find("check_clause_0") != std::string::npos);

    std::cout << "  ✓ Emit single clause\n";
}

void test_emit_multiple_clauses() {
    LLVMEmitter emitter;
    std::vector<Clause> clauses = {
        {1, 2, -3},
        {-1, 2},
        {-2, 3}
    };

    std::string ir = emitter.emit_module(clauses);
    assert(ir.find("constraint_0") != std::string::npos);
    assert(ir.find("constraint_1") != std::string::npos);
    assert(ir.find("constraint_2") != std::string::npos);
    assert(ir.find("check_clause_0") != std::string::npos);
    assert(ir.find("check_clause_1") != std::string::npos);
    assert(ir.find("check_clause_2") != std::string::npos);

    // Check clause sizes in globals
    assert(ir.find("i64 3,") != std::string::npos);  // clause 0 has 3 lits
    assert(ir.find("i64 2,") != std::string::npos);  // clause 1 has 2 lits

    std::cout << "  ✓ Emit multiple clauses\n";
}

void test_emit_clause_check() {
    LLVMEmitter emitter;
    Clause clause = {1, -2, 3};

    std::string ir = emitter.emit_clause_check(clause, 5);
    assert(ir.find("Clause 5") != std::string::npos);
    assert(ir.find("clause5_result") != std::string::npos);
    assert(ir.find("lit1_pos") != std::string::npos);
    assert(ir.find("lit2_neg") != std::string::npos);
    assert(ir.find("lit3_pos") != std::string::npos);

    std::cout << "  ✓ Emit clause check\n";
}

void test_emit_no_avx512() {
    EmitterConfig config;
    config.avx512 = false;
    LLVMEmitter emitter(config);

    std::vector<Clause> clauses = {{1, 2}};
    std::string ir = emitter.emit_module(clauses);

    assert(ir.find("AVX-512: disabled") != std::string::npos);
    assert(ir.find("check_batch_avx512") == std::string::npos);

    std::cout << "  ✓ Emit without AVX-512\n";
}

void test_emit_with_avx512() {
    EmitterConfig config;
    config.avx512 = true;
    LLVMEmitter emitter(config);

    std::vector<Clause> clauses = {{1, 2}};
    std::string ir = emitter.emit_module(clauses);

    assert(ir.find("AVX-512: enabled") != std::string::npos);
    assert(ir.find("check_batch_avx512") != std::string::npos);
    assert(ir.find("icmp sge <16 x i32>") != std::string::npos);

    std::cout << "  ✓ Emit with AVX-512\n";
}

void test_emit_cache_aligned() {
    EmitterConfig config;
    config.cache_aligned = true;
    LLVMEmitter emitter(config);

    std::vector<Clause> clauses = {{1}};
    std::string ir = emitter.emit_module(clauses);

    assert(ir.find("align 64") != std::string::npos);
    assert(ir.find("64-byte") != std::string::npos);

    std::cout << "  ✓ Emit cache-aligned\n";
}

void test_emit_not_cache_aligned() {
    EmitterConfig config;
    config.cache_aligned = false;
    LLVMEmitter emitter(config);

    std::vector<Clause> clauses = {{1}};
    std::string ir = emitter.emit_module(clauses);

    assert(ir.find("Cache-aligned: default") != std::string::npos);

    std::cout << "  ✓ Emit not cache-aligned\n";
}

void test_emit_footer() {
    LLVMEmitter emitter;
    std::vector<Clause> clauses = {{1}};
    std::string ir = emitter.emit_module(clauses);

    assert(ir.find("End of generated LLVM IR") != std::string::npos);
    assert(ir.find("llc -mattr=+avx512f") != std::string::npos);

    std::cout << "  ✓ Emit footer present\n";
}

void test_emit_from_solver() {
    // Integration: use solver clauses directly with emitter
    CDCLSolver solver;
    solver.add_clause({1, 2, -3});
    solver.add_clause({-1, 2});
    solver.add_clause({-2, 3});

    LLVMEmitter emitter;
    std::string ir = emitter.emit_module(solver.clauses());

    assert(ir.find("constraint_0") != std::string::npos);
    assert(ir.find("constraint_1") != std::string::npos);
    assert(ir.find("constraint_2") != std::string::npos);

    std::cout << "  ✓ Emit from solver clauses\n";
}

void test_emit_empty_clause() {
    LLVMEmitter emitter;
    std::vector<Clause> clauses = {{}};

    std::string ir = emitter.emit_module(clauses);
    assert(ir.find("ret i1 true") != std::string::npos);

    std::cout << "  ✓ Emit empty clause\n";
}

int main() {
    std::cout << "=== Emitter Tests ===\n";
    test_emit_empty();
    test_emit_single_clause();
    test_emit_multiple_clauses();
    test_emit_clause_check();
    test_emit_no_avx512();
    test_emit_with_avx512();
    test_emit_cache_aligned();
    test_emit_not_cache_aligned();
    test_emit_footer();
    test_emit_from_solver();
    test_emit_empty_clause();
    std::cout << "\nAll emitter tests passed!\n";
    return 0;
}
