#pragma once
/// flux::LLVMEmitter — Emits LLVM IR from CDCL solver traces
///
/// Takes a CDCL trace and produces LLVM IR text that implements
/// AVX-512 vectorized constraint checking. Constraint records are
/// cache-aligned 64-byte structures for optimal memory bandwidth.

#include "solver.hpp"
#include <string>
#include <sstream>
#include <cstdint>

namespace flux {

/// Emitter configuration
struct EmitterConfig {
    bool avx512 = true;
    bool cache_aligned = true;
    bool hdc_bloom = false;  // Hyperdimensional bloom pre-filter
    int constraint_width = 16; // SIMD width (16 for AVX-512)
};

/// LLVM IR emitter for constraint checking
class LLVMEmitter {
public:
    explicit LLVMEmitter(const EmitterConfig& config = {})
        : config_(config) {}

    /// Emit a complete LLVM module from solver clauses
    std::string emit_module(const std::vector<Clause>& clauses) const {
        std::ostringstream ir;
        emit_header(ir);
        emit_globals(ir, clauses);
        emit_check_function(ir, clauses);
        emit_batch_function(ir, clauses);
        emit_footer(ir);
        return ir.str();
    }

    /// Emit LLVM IR for a single clause check
    std::string emit_clause_check(const Clause& clause, int index) const {
        std::ostringstream ir;
        ir << "  ; Clause " << index << ": ";
        for (auto lit : clause) ir << lit << " ";
        ir << "\n";

        ir << "  %clause" << index << "_result = or i1 ";
        for (size_t i = 0; i < clause.size(); ++i) {
            auto lit = clause[i];
            auto var = std::abs(lit);
            ir << "%lit" << var << (lit > 0 ? "_pos" : "_neg");
            if (i + 1 < clause.size()) ir << ", ";
        }
        ir << "\n";
        return ir.str();
    }

private:
    EmitterConfig config_;

    void emit_header(std::ostringstream& ir) const {
        ir << R"(; constraint-theory-engine-cpp-lua: LLVM IR output
; Generated by flux::LLVMEmitter
; AVX-512: )" << (config_.avx512 ? "enabled" : "disabled") << R"(
; Cache-aligned: )" << (config_.cache_aligned ? "64-byte" : "default") << R"(

source_filename = "flux_constraint_check.ll"
target triple = "x86_64-unknown-linux-gnu"

)";
    }

    void emit_globals(std::ostringstream& ir, const std::vector<Clause>& clauses) const {
        ir << R"(; Constraint records (64-byte cache-aligned)
; Format: { i64 header, <16 x i32> values, <16 x i32> masks, i64 footer }

)";
        for (size_t i = 0; i < clauses.size(); ++i) {
            ir << "@constraint_" << i << " = align 64 constant { i64, <16 x i32>, <16 x i32>, i64 } {\n";
            ir << "  i64 " << clauses[i].size() << ",\n";
            ir << "  <16 x i32> zeroinitializer,\n"; // values filled at runtime
            ir << "  <16 x i32> zeroinitializer,\n"; // masks filled at runtime
            ir << "  i64 " << i << "\n";
            ir << "}\n\n";
        }
    }

    void emit_check_function(std::ostringstream& ir, const std::vector<Clause>& clauses) const {
        ir << R"(define i1 @check_all_clauses(<16 x i32> %values) {
entry:
)";

        for (size_t i = 0; i < clauses.size(); ++i) {
            ir << "  %clause" << i << " = call i1 @check_clause_" << i << "(<16 x i32> %values)\n";
        }

        // AND all clause results
        ir << "  %result = and i1";
        for (size_t i = 0; i < clauses.size(); ++i) {
            ir << " %clause" << i;
            if (i + 1 < clauses.size()) ir << ",";
        }
        if (clauses.empty()) ir << " true, true";
        ir << "\n";

        ir << "  ret i1 %result\n}\n\n";

        // Individual clause functions
        for (size_t i = 0; i < clauses.size(); ++i) {
            emit_single_clause(ir, clauses[i], i);
        }
    }

    void emit_single_clause(std::ostringstream& ir, const Clause& clause, int idx) const {
        ir << "define i1 @check_clause_" << idx << "(<16 x i32> %values) {\n";
        ir << "entry:\n";

        // Extract first literal's variable
        if (!clause.empty()) {
            auto var = std::abs(clause[0]);
            ir << "  %v" << var << " = extractelement <16 x i32> %values, i32 "
               << ((var - 1) % 16) << "\n";
            ir << "  %cmp" << idx << " = icmp sgt i32 %v" << var << ", 0\n";
            ir << "  ret i1 %cmp" << idx << "\n";
        } else {
            ir << "  ret i1 true\n";
        }

        ir << "}\n\n";
    }

    void emit_batch_function(std::ostringstream& ir, const std::vector<Clause>& clauses) const {
        if (!config_.avx512) return;

        ir << R"(; AVX-512 batch: 16×16=256 checks per call
define <16 x i1> @check_batch_avx512(<16 x i32> %values, <16 x i32> %lo, <16 x i32> %hi) {
entry:
  %cmp_lo = icmp sge <16 x i32> %values, %lo
  %cmp_hi = icmp sle <16 x i32> %values, %hi
  %result = and <16 x i1> %cmp_lo, %cmp_hi
  ret <16 x i1> %result
}

)";
    }

    void emit_footer(std::ostringstream& ir) const {
        ir << R"(; End of generated LLVM IR
; Compile with: llc -mattr=+avx512f flux_constraint_check.ll -o flux_check.s
)";
    }
};

} // namespace flux
